name: Release userscript

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Get version
        id: package-version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          files: dist/*.user.js